# This file was generated by https://github.com/kamilchm/go2nix v1.2.1
{ stdenv, buildGoPackage, fetchgit, fetchhg, fetchbzr, fetchsvn }:

buildGoPackage rec {
  name = "holo-cli-unstable-${version}";
  version = "2019-04-08";
  rev = "7d24a08b861be9aae8c30b3bca7f513432b76f89";

  goPackagePath = "github.com/Holo-Host/holo-cli";

  src = fetchgit {
    inherit rev;
    url = "https://github.com/Holo-Host/holo-cli.git";
    sha256 = "10prifhc8w1n699083srv73wmn80wmzbpvydk09kgar7rx4xkzds";
  };

  goDeps = ./deps.nix;

  # TODO: add metadata https://nixos.org/nixpkgs/manual/#sec-standard-meta-attributes
  meta = with stdenv.lib; {
    description = "holo-cli";
    homepage    = https://github.com/Holo-Host/holo-cli;
    license     = licenses.free;
    platforms   = platforms.unix;
    maintainers = [ maintainers.samrose ];

  };
}
