# This file was generated by https://github.com/kamilchm/go2nix v1.2.1
[
  {
    goPackagePath = "github.com/chzyer/readline";
    fetch = {
      type = "git";
      url = "https://github.com/chzyer/readline";
      rev = "2972be24d48e78746da79ba8e24e8b488c9880de";
      sha256 = "104q8dazj8yf6b089jjr82fy9h1g80zyyzvp3g8b44a7d8ngjj6r";
    };
  }
  {
    goPackagePath = "github.com/fsnotify/fsnotify";
    fetch = {
      type = "git";
      url = "https://github.com/fsnotify/fsnotify";
      rev = "1485a34d5d5723fea214f5710708e19a831720e4";
      sha256 = "0h2g3603z3zsnagxv5dlgzclq1hp2b95wl7c0k4m9ccaif4i8hjf";
    };
  }
  {
    goPackagePath = "github.com/hashicorp/hcl";
    fetch = {
      type = "git";
      url = "https://github.com/hashicorp/hcl";
      rev = "65a6292f0157eff210d03ed1bf6c59b190b8b906";
      sha256 = "00qgmygfa4vgf9v3lpz4vp1ca1hcfcxnjqjrvp6z4jjklc8x4mqf";
    };
  }
  {
    goPackagePath = "github.com/juju/ansiterm";
    fetch = {
      type = "git";
      url = "https://github.com/juju/ansiterm";
      rev = "720a0952cc2ac777afc295d9861263e2a4cf96a1";
      sha256 = "0n6j0y7xhashp8gdkdl0r7vlbkdrkymrzxn9hxrx522k2isggs7h";
    };
  }
  {
    goPackagePath = "github.com/lunixbochs/vtclean";
    fetch = {
      type = "git";
      url = "https://github.com/lunixbochs/vtclean";
      rev = "88cfb0c2efe8ed7b0ccf0af83db39359829027bb";
      sha256 = "0jqn33l1kzy4dk66zbvxz7rlgkgg34s9mhc8z0lrz0i88466zhd8";
    };
  }
  {
    goPackagePath = "github.com/magiconair/properties";
    fetch = {
      type = "git";
      url = "https://github.com/magiconair/properties";
      rev = "7757cc9fdb852f7579b24170bcacda2c7471bb6a";
      sha256 = "1v3b69834k0pp4q238s8srx2f0kgxdy8i6akxdanmhldm6ajs035";
    };
  }
  {
    goPackagePath = "github.com/manifoldco/promptui";
    fetch = {
      type = "git";
      url = "https://github.com/manifoldco/promptui";
      rev = "ae9f05e7444d215f8a681daa7ff9b5a822645167";
      sha256 = "16lr9kmbsaqsyr7h7n26mg97afzsngw15yxvzin0h929fch87kh8";
    };
  }
  {
    goPackagePath = "github.com/mattn/go-colorable";
    fetch = {
      type = "git";
      url = "https://github.com/mattn/go-colorable";
      rev = "3a70a971f94a22f2fa562ffcc7a0eb45f5daf045";
      sha256 = "0l640974j804c1yyjfgyxqlsivz0yrzmbql4mhcw2azryigkp08p";
    };
  }
  {
    goPackagePath = "github.com/mattn/go-isatty";
    fetch = {
      type = "git";
      url = "https://github.com/mattn/go-isatty";
      rev = "c2a7a6ca930a4cd0bc33a3f298eb71960732a3a7";
      sha256 = "1i77aq4gf9as03m8fpfh8fq49n4z9j7548blrcsidm1xhslzk5xd";
    };
  }
  {
    goPackagePath = "github.com/mitchellh/go-homedir";
    fetch = {
      type = "git";
      url = "https://github.com/mitchellh/go-homedir";
      rev = "af06845cf3004701891bf4fdb884bfe4920b3727";
      sha256 = "0ydzkipf28hwj2bfxqmwlww47khyk6d152xax4bnyh60f4lq3nx1";
    };
  }
  {
    goPackagePath = "github.com/mitchellh/mapstructure";
    fetch = {
      type = "git";
      url = "https://github.com/mitchellh/mapstructure";
      rev = "3536a929edddb9a5b34bd6861dc4a9647cb459fe";
      sha256 = "03bpv28jz9zhn4947saqwi328ydj7f6g6pf1m2d4m5zdh5jlfkrr";
    };
  }
  {
    goPackagePath = "github.com/pelletier/go-toml";
    fetch = {
      type = "git";
      url = "https://github.com/pelletier/go-toml";
      rev = "63909f0a90ab0f36909e8e044e46ace10cf13ba2";
      sha256 = "04043a9k9ny9fci423iv8dz2s2i5ysrkcncl6wsfl8xcvamkb6c9";
    };
  }
  {
    goPackagePath = "github.com/spf13/afero";
    fetch = {
      type = "git";
      url = "https://github.com/spf13/afero";
      rev = "588a75ec4f32903aa5e39a2619ba6a4631e28424";
      sha256 = "0j9r65qgd58324m85lkl49vk9dgwd62g7dwvkfcm3k6i9dc555a9";
    };
  }
  {
    goPackagePath = "github.com/spf13/cast";
    fetch = {
      type = "git";
      url = "https://github.com/spf13/cast";
      rev = "8c9545af88b134710ab1cd196795e7f2388358d7";
      sha256 = "0xq1ffqj8y8h7dcnm0m9lfrh0ga7pssnn2c1dnr09chqbpn4bdc5";
    };
  }
  {
    goPackagePath = "github.com/spf13/cobra";
    fetch = {
      type = "git";
      url = "https://github.com/spf13/cobra";
      rev = "67fc4837d267bc9bfd6e47f77783fcc3dffc68de";
      sha256 = "1k7dq78fjz94lzifsprkmiv93swwzwcbg1vd64v20wvnga8v254b";
    };
  }
  {
    goPackagePath = "github.com/spf13/jwalterweatherman";
    fetch = {
      type = "git";
      url = "https://github.com/spf13/jwalterweatherman";
      rev = "94f6ae3ed3bceceafa716478c5fbf8d29ca601a1";
      sha256 = "1ywmkwci5zyd88ijym6f30fj5c0k2yayxarkmnazf5ybljv50q7b";
    };
  }
  {
    goPackagePath = "github.com/spf13/pflag";
    fetch = {
      type = "git";
      url = "https://github.com/spf13/pflag";
      rev = "24fa6976df40757dce6aea913e7b81ade90530e1";
      sha256 = "0rf6prz6gl0l1b3wijzdgq887cdwigvzxvz6gqbm5l8pkq3fx1m9";
    };
  }
  {
    goPackagePath = "github.com/spf13/viper";
    fetch = {
      type = "git";
      url = "https://github.com/spf13/viper";
      rev = "7a605a50e69cd1ea431c4a1e6eebe9b287ef6de4";
      sha256 = "0sfb2nsi8mi90cshzycmigrff055my72q2lz2rm52cqrmdy25a5q";
    };
  }
  {
    goPackagePath = "golang.org/x/sys";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/sys";
      rev = "4b34438f7a67ee5f45cc6132e2bad873a20324e9";
      sha256 = "1xnsiaikz62wqjpaly1j4nqwp504gih5mgw9wdj1pp1d4bmx0vl0";
    };
  }
  {
    goPackagePath = "golang.org/x/text";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/text";
      rev = "31e7599a6c37728c25ca34167be099d072ad335d";
      sha256 = "18i17j7nkkc5dl9rpzm8l345r409hfj4knfnldar684337x1irrf";
    };
  }
  {
    goPackagePath = "gopkg.in/yaml.v2";
    fetch = {
      type = "git";
      url = "https://gopkg.in/yaml.v2";
      rev = "51d6538a90f86fe93ac480b35f37b2be17fef232";
      sha256 = "01wj12jzsdqlnidpyjssmj0r4yavlqy7dwrg7adqd8dicjc4ncsa";
    };
  }
]